version: '3'
services:
  server:
    image: clickhouse/clickhouse-server:23
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_ADMIN_PASSWORD=Admin123
      - TZ=Asia/Shanghai
      # - CLICKHOUSE_DB=jquant
      # - CLICKHOUSE_USER=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=admin123
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9005:9005"
      - "9009:9009"
    volumes:
      - /opt/clickhouse/data:/var/lib/clickhouse/
      - /opt/clickhouse/logs:/var/log/clickhouse-server/