version: '3.8'

services:
  mqnamesrv:
    image: apache/rocketmq:5.1.3
    restart: always
    network_mode: host
    # mem_limit: 4G
    command:
      - './mqnamesrv'
    ports:
      - '9876:9876'

  mqbroker:
    image: apache/rocketmq:5.1.3
    network_mode: host
    restart: always
    # mem_limit: 10G
    environment:
      NAMESRV_ADDR: '172.16.6.15:9876'
    depends_on:
      - mqnamesrv
    volumes:
      - ./store:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq/rocketmq-5.1.3/conf/broker.conf
      - ./rmq-proxy.json:/home/rocketmq/rocketmq-5.1.3/conf/rmq-proxy.json
    command:
      - './mqbroker'
      - '-n'
      - '172.16.6.15:9876'
      - '--enable-proxy'
    ports:
      - '8081:8081'
      - '10911:10911'
      - '10909:10909'
  mqdashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    restart: always
    network_mode: host
    mem_limit: 512M
    environment:
      JAVA_OPTS: '-Drocketmq.namesrv.addr=172.16.6.15:9876'
    depends_on:
      - mqnamesrv
    ports:
      - '9090:8080'
