services:
  namesrv:
    image: apache/rocketmq:5.1.3
    restart: always
    networks:
      - rocketmq
    # mem_limit: 4G
    command:
      - 'sh'
      - 'mqnamesrv'
    ports:
      - 9876:9876
  broker:
    image: apache/rocketmq:5.1.3
    networks:
      - rocketmq
    restart: always
    # mem_limit: 10G
    environment:
      - NAMESRV_ADDR=192.168.100.160:9876
    depends_on:
      - namesrv
    volumes:
      - ./store:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq/rocketmq-5.1.3/conf/broker.conf
      - ./rmq-proxy.json:/home/rocketmq/rocketmq-5.1.3/conf/rmq-proxy.json
    command:
      - 'sh'
      - 'mqbroker'
      - '-n'
      - '192.168.100.160:9876'
      - '--enable-proxy'
    ports:
      - 18080:18080
      - 18081:18081      
      - 10909:10909
      - 10911:10911
      - 10912:10912
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    restart: always
    mem_limit: 512M
    environment:
      JAVA_OPTS: '-Drocketmq.namesrv.addr=192.168.100.160:9876'
    depends_on:
      - namesrv
    ports:
      - 18082:8082
networks:
  rocketmq:
    driver: bridge