version: '3'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.13-management
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin123
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - /opt/rabbitmq/lib:/var/lib/rabbitmq
    - /opt/rabbitmq/log:/var/log/rabbitmq

