[project]
name = "python-pdf"
version = "0.0.1"
description = ""
authors = [
    {name = "enoch",email = "lanxenet@gmail.com"},
]
dependencies = [
    "pymupdf4llm>=0.0.17",
    "ollama>=0.3.3",
    "surya-ocr>=0.6.13",
    "streamlit>=1.40.2",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false
[tool.pdm.dev-dependencies]
dev = [
    "black>=24.8.0",
    "pytest-asyncio>=0.24.0",
]
[tool.pytest.ini_options]
addopts = "-v -s"
asyncio_mode = "auto"
log_cli = true
log_level = "NOTSET"
testpaths = [
    "tests",
    "src",
]
python_files = [
    "test_*.py",
    "*_test.py",
]