version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:4.13
    shm_size: 2gb
    networks:
      - selenium
    ports:
      - "4444:4444"
      - "7900:7900"
  robot:
    image: registry.cn-hangzhou.aliyuncs.com/base_containers/selenium:ocr-0.1.3
    depends_on:
      - chrome  
    networks:
      - selenium
    environment:
      - WEB_DRIVER_URL=http://chrome:4444/wd/hub
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  selenium:
